connector_image: buildkite-source
tests:
  spec:
    - config_path: "secrets/config.json"
      spec_path: "test_files/spec.json" 
  incremental:
    - config_path: "secrets/config.json"
      configured_catalog_path: "test_files/incremental_configured_catalog.json"
      future_state_path: "test_files/abnormal_state.json"
      cursor_paths:
      // TODO: build just for example
        build: ["cutoff"]
