name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      FORCE_COLOR: true
      HUSKY_SKIP_INSTALL: 1
      HUSKY_SKIP_HOOKS: 1
      HUSKY: 0

    steps:
      - name: Check out
        uses: actions/checkout@v2.4.0

      - name: Source Acceptance Test
        if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }} # Skip PRs
        env:
          PAGERDUTY_SOURCE_TEST_CONFIG: ${{ secrets.PAGERDUTY_SOURCE_TEST_CONFIG }}
        run: |
          for i in $(ls -d sources/*/)
          do
            source=$(echo $i | cut -f2 -d'/')
            case "$source" in
              pagerduty-source)
                ./scripts/source-acceptance-test.sh $source
                ;;
              *)
                echo "Skipping $source acceptance tests"
                ;;
            esac
          done
